"""Write src/gate_data.rs: every instruction of Stim's circuit language, with what
``stim.gate_data`` says of it (names, flags, argument counts, tableau, unitary matrix, flows,
inverses and Hadamard conjugate), for ``stabilizer_qec.gate_data`` and ``GateData``.

    STIM_SRC=path/to/stim/src/stim python tools/gen_gate_data.py           # rewrite src/gate_data.rs
    STIM_SRC=path/to/stim/src/stim python tools/gen_gate_data.py --check   # fail if it differs

Most of it comes from the installed ``stim``. Stim's internal gate flags (which instructions
take pairs, fuse with their neighbours, take only records, ...), argument counts, help
categories and H/S/CX/M/R decompositions are not exposed in Python, so they are read from
Stim's own gate definitions (``src/stim/gates/gate_data_*.cc`` of the matching source release)
at ``STIM_SRC``.

These are facts about the language, read from Stim (Apache-2.0) and checked against it by
tests/test_gate_data.py; the help text built from them is our own.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

import numpy as np
import stim

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "gate_data.rs"

FLAGS = [
    "is_noisy_gate",
    "is_reset",
    "is_single_qubit_gate",
    "is_symmetric_gate",
    "is_two_qubit_gate",
    "is_unitary",
    "produces_measurements",
    "takes_measurement_record_targets",
    "takes_pauli_targets",
]


SOURCE_FLAGS = [
    "GATE_IS_UNITARY",
    "GATE_IS_NOISY",
    "GATE_ARGS_ARE_DISJOINT_PROBABILITIES",
    "GATE_PRODUCES_RESULTS",
    "GATE_IS_NOT_FUSABLE",
    "GATE_IS_BLOCK",
    "GATE_TARGETS_PAIRS",
    "GATE_TARGETS_PAULI_STRING",
    "GATE_ONLY_TARGETS_MEASUREMENT_RECORD",
    "GATE_CAN_TARGET_BITS",
    "GATE_TAKES_NO_TARGETS",
    "GATE_ARGS_ARE_UNSIGNED_INTEGERS",
    "GATE_TARGETS_COMBINERS",
    "GATE_IS_RESET",
    "GATE_HAS_NO_EFFECT_ON_QUBITS",
    "GATE_IS_SINGLE_QUBIT_GATE",
]


def source_gates() -> dict:
    """name -> (flags bitmask, arg_count, category, decomposition text) from Stim's sources."""
    root = os.environ.get("STIM_SRC")
    if not root:
        raise SystemExit("set STIM_SRC to Stim's src/stim directory (from the sdist of the installed version)")
    out = {}
    for f in sorted(Path(root, "gates").glob("gate_data_*.cc")):
        text = f.read_text()
        for block in re.split(r"\bGate\{", text)[1:]:
            m = re.search(r'\.name = "([^"]+)"', block)
            if m is None:
                continue
            name = m.group(1)
            argc = re.search(r"\.arg_count = ([A-Z_0-9]+)", block).group(1)
            argc = {"ARG_COUNT_SYGIL_ANY": 255, "ARG_COUNT_SYGIL_ZERO_OR_ONE": 254}.get(argc, None) if not argc.isdigit() else int(argc)
            m = re.search(r"\.flags\s*=\s*(.*?),\s*\n\s*\.", block, re.S)
            flags_text = m.group(1) if m else ""
            bits = 0
            for k, flag in enumerate(SOURCE_FLAGS):
                if re.search(r"\b" + flag + r"\b", flags_text):
                    bits |= 1 << k
            cat = re.search(r'\.category = "([^"]*)"', block).group(1)
            inv = re.search(r"\.best_candidate_inverse_id = GateType::([A-Z_0-9]+)", block).group(1)
            dec = re.search(r'\.h_s_cx_m_r_decomposition = R"CIRCUIT\((.*?)\)CIRCUIT"', block, re.S)
            out[name] = (bits, argc, cat, dec.group(1).strip("\n") if dec else None, inv)
    return out


def canonical_type(type_name: str, data: dict) -> str:
    """A GateType enum name (e.g. ZCX in old sources, or CX) as the gate's canonical name."""
    return stim.gate_data(type_name).name


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def entry(c: complex) -> str:
    re, im = float(np.real(c)), float(np.imag(c))
    return f"({re!r}, {im!r})"


def render() -> str:
    data = stim.gate_data()
    src = source_gates()
    missing = sorted(set(data) - set(src))
    if missing:
        raise SystemExit(f"no source definition for {missing}")
    lines = [
        "//! Every instruction of Stim's circuit language, as `stim.gate_data` describes it: names,",
        "//! flags, argument counts, tableau, unitary matrix, flows, inverses and Hadamard conjugate.",
        "//! Generated by tools/gen_gate_data.py (Stim " + stim.__version__ + "); do not edit.",
        "",
        "/// One instruction's data. `tableau` is Stim's: the images of X and Z of each target, as",
        "/// signed Pauli strings (`x0, z0` for one qubit; `x0, z0, x1, z1` for two). `unitary` is",
        "/// row-major (re, im), in Stim's little-endian qubit order. `flows` are Stim's example flows.",
        "#[derive(Debug)]",
        "pub struct GateInfo {",
        "    pub name: &'static str,",
        "    pub aliases: &'static [&'static str],",
    ]
    lines += [f"    pub {f}: bool," for f in FLAGS]
    lines += [
        "    /// `num_parens_arguments_range` as (start, stop): Python's range(start, stop).",
        "    pub args: (u16, u16),",
        "    pub tableau: &'static [&'static str],",
        "    pub unitary: &'static [(f64, f64)],",
        "    pub flows: &'static [&'static str],",
        "    pub inverse: Option<&'static str>,",
        "    pub generalized_inverse: &'static str,",
        "    pub hadamard_conjugated: Option<&'static str>,",
        "    /// The same up to Pauli signs (`hadamard_conjugated(unsigned=True)`).",
        "    pub hadamard_conjugated_unsigned: Option<&'static str>,",
        "    /// Stim's internal flags (the `FLAG_*` bits below).",
        "    pub flags: u32,",
        "    /// How many parens arguments: a count, or 254 (zero or one) or 255 (any).",
        "    pub arg_count: u8,",
        "    /// Stim's help category, e.g. \"B_Single Qubit Clifford Gates\".",
        "    pub category: &'static str,",
        "    /// Stim's decomposition into H, S, CX, M and R (empty for none).",
        "    pub decomposition: &'static str,",
        "    /// Stim's `best_candidate_inverse_id`: the gate `Circuit.inverse` writes for this one.",
        "    pub inverse_candidate: &'static str,",
        "}",
        "",
    ]
    for k, flag in enumerate(SOURCE_FLAGS):
        lines.append(f"pub const FLAG_{flag[5:]}: u32 = 1 << {k};")
    lines += [
        "",
        "pub const GATE_INFO: &[GateInfo] = &[",
    ]
    for key in sorted(data):
        g = data[key]
        tab = []
        if g.is_unitary and (g.is_single_qubit_gate or g.is_two_qubit_gate):
            t = g.tableau
            for q in range(len(t)):
                tab += [str(t.x_output(q)), str(t.z_output(q))]
        unitary = []
        if g.is_unitary and (g.is_single_qubit_gate or g.is_two_qubit_gate):
            unitary = [entry(c) for c in np.asarray(g.unitary_matrix).flatten()]
        flows = [str(f) for f in (g.flows or [])]
        inv = g.inverse.name if g.inverse is not None else None
        try:
            hc = g.hadamard_conjugated()
            hc = hc.name if hc is not None else None
        except Exception:
            hc = None
        try:
            hcu = g.hadamard_conjugated(unsigned=True)
            hcu = hcu.name if hcu is not None else None
        except Exception:
            hcu = None
        r = g.num_parens_arguments_range
        fields = [
            f"name: {rust_str(g.name)}",
            "aliases: &[" + ", ".join(rust_str(a) for a in sorted(g.aliases)) + "]",
        ]
        fields += [f"{f}: {str(getattr(g, f)).lower()}" for f in FLAGS]
        fields += [
            f"args: ({r.start}, {r.stop})",
            "tableau: &[" + ", ".join(rust_str(s) for s in tab) + "]",
            "unitary: &[" + ", ".join(unitary) + "]",
            "flows: &[" + ", ".join(rust_str(s) for s in flows) + "]",
            f"inverse: {'Some(' + rust_str(inv) + ')' if inv else 'None'}",
            f"generalized_inverse: {rust_str(g.generalized_inverse.name)}",
            f"hadamard_conjugated: {'Some(' + rust_str(hc) + ')' if hc else 'None'}",
            f"hadamard_conjugated_unsigned: {'Some(' + rust_str(hcu) + ')' if hcu else 'None'}",
            f"flags: {src[key][0]}",
            f"arg_count: {src[key][1]}",
            f"category: {rust_str(src[key][2])}",
            f"decomposition: {rust_str(src[key][3] or '')}",
            f"inverse_candidate: {rust_str(canonical_type(src[key][4], data))}",
        ]
        lines.append("    GateInfo { " + ", ".join(fields) + " },")
    lines += [
        "];",
        "",
        "/// The instruction a name or alias denotes, case-insensitively, as Stim reads names.",
        "pub fn info(name: &str) -> Option<&'static GateInfo> {",
        "    let upper = name.to_ascii_uppercase();",
        "    GATE_INFO.iter().find(|g| g.name == upper || g.aliases.contains(&upper.as_str()))",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit("src/gate_data.rs differs from what tools/gen_gate_data.py writes")
        print("src/gate_data.rs is current")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
