"""Write src/gates.rs: every unitary one- and two-qubit gate of Stim's, as the shortest sequence
of H, S and CX whose tableau equals Stim's exactly, signs included.

    python tools/gen_gates.py           # rewrite src/gates.rs
    python tools/gen_gates.py --check   # fail if src/gates.rs differs from what Stim gives now

The search is breadth-first over the Clifford group (one qubit: 24 elements with signs; two:
11,520 times the 16 sign choices), so each decomposition is a shortest one, and every one is
checked against Stim's tableau before it is written.
"""

from __future__ import annotations

import sys
from collections import deque
from pathlib import Path

import stim

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "gates.rs"

# The engine's own primitives: these keep their instructions.
NATIVE = {"H", "X", "Y", "Z", "I", "CX", "CZ", "S"}


def search(arity: int) -> dict:
    """Every element of the signed Clifford group on `arity` qubits, with a shortest word."""
    if arity == 1:
        gens = [("H", (0,)), ("S", (0,))]
    else:
        gens = [("H", (0,)), ("H", (1,)), ("S", (0,)), ("S", (1,)), ("CX", (0, 1)), ("CX", (1, 0))]
    gen_tab = [stim.Circuit(f"{g} {' '.join(map(str, t))}").to_tableau() for g, t in gens]
    if arity == 2:
        gen_tab = [t if len(t) == 2 else t + stim.Tableau(1) for t in gen_tab]
    start = stim.Tableau(arity)
    words = {str(start): []}
    queue = deque([(start, [])])
    while queue:
        tab, word = queue.popleft()
        for (g, t), gt in zip(gens, gen_tab):
            if len(gt) != arity:  # a one-qubit generator on qubit 1 of a pair
                gt = stim.Tableau(1) + gt
            nxt = tab.then(gt)
            key = str(nxt)
            if key not in words:
                words[key] = word + [(g, t)]
                queue.append((nxt, words[key]))
    return words


def gates() -> list:
    """(name, arity, word, aliases) for every unitary Stim gate the engine does not have."""
    out = []
    seen = set()
    for name, g in sorted(stim.gate_data().items()):
        if g.name in seen or g.name in NATIVE or not g.is_unitary:
            continue
        if not (g.is_single_qubit_gate or g.is_two_qubit_gate):
            continue
        seen.add(g.name)
        out.append((g.name, 1 if g.is_single_qubit_gate else 2, g.tableau, sorted(a for a in g.aliases if a != g.name)))
    return out


def word_tableau(word: list, arity: int) -> stim.Tableau:
    text = "\n".join(f"{g} {' '.join(map(str, t))}" for g, t in word)
    c = stim.Circuit(text)
    tab = c.to_tableau() if len(c) else stim.Tableau(arity)
    while len(tab) < arity:
        tab = tab + stim.Tableau(1)
    return tab


def render() -> str:
    words = {1: search(1), 2: search(2)}
    lines = [
        "//! Every unitary one- and two-qubit gate of Stim's that the engine does not have as an",
        "//! instruction of its own, as the shortest sequence of H, S and CX whose tableau equals",
        "//! Stim's exactly, signs included. Generated by tools/gen_gates.py (Stim "
        + stim.__version__
        + "); do not edit.",
        "",
        "/// One step of a decomposition, on the gate's target slots (0, or 0 and 1).",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum Step {",
        "    H(u8),",
        "    S(u8),",
        "    Cx(u8, u8),",
        "}",
        "",
        "/// A gate: its name, how many targets it takes, its decomposition and its other names.",
        "pub struct GateDef {",
        "    pub name: &'static str,",
        "    pub arity: u8,",
        "    pub steps: &'static [Step],",
        "    pub aliases: &'static [&'static str],",
        "}",
        "",
        "pub const GATES: &[GateDef] = &[",
    ]
    for name, arity, tab, aliases in gates():
        word = words[arity].get(str(tab))
        if word is None:
            raise SystemExit(f"no decomposition found for {name}")
        if word_tableau(word, arity) != tab:
            raise SystemExit(f"the decomposition of {name} does not reproduce Stim's tableau")
        steps = ", ".join(
            f"Step::{ {'H': 'H', 'S': 'S', 'CX': 'Cx'}[g] }({', '.join(map(str, t))})" for g, t in word
        )
        alias_text = ", ".join(f'"{a}"' for a in aliases)
        lines.append(f'    GateDef {{ name: "{name}", arity: {arity}, steps: &[{steps}], aliases: &[{alias_text}] }},')
    lines += [
        "];",
        "",
        "/// The gate a name (or alias) denotes.",
        "pub fn find(name: &str) -> Option<&'static GateDef> {",
        "    GATES.iter().find(|g| g.name == name || g.aliases.contains(&name))",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit("src/gates.rs differs from what tools/gen_gates.py writes")
        print("src/gates.rs is current")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
